### ISSUE TITLE
Terminate Execution from within Interceptor

### ISSUE THREAD

**Issue by CodeMeister** [renz45/mandrill_mailer#107]
Feature Request:

Add the option to terminate the sending process from within an Interceptor.

Scenario:  On our 'staging' server I only want emails with specific addresses to be sent.  Within the Interceptor I can easily replace the non-allowed emails with specific dummy email address, but it would be much simpler to be able to terminate the mail and not send it at all.

Great Gem by the way :-)

**Comment by renz45** [comment]
Thanks for the suggestion. If I might make a suggestion for this feature, maybe a config setting for a white/blacklist of un/accepted emails might be more appropriate?

If that sounds odd, then maybe returning false from the interceptor prevents the email from being sent. I don't use the interceptors much myself, but I always thought of them as a sort of... filter in a way instead of flow control, which makes me gravitate to the white/blacklist idea. Granted the config wouldn't be able to be modified as easily at runtime if dynamic blocking was needed.

**Comment by renz45** [comment]
Closing this since it's been a year, feel free to reopen or make a PR for it :)
