### ISSUE TITLE
use mandrill_mailer with letter_opener for development enviroments

### ISSUE THREAD

**Issue by nmenag** [renz45/mandrill_mailer#108]
it is posible?

**Comment by renz45** [comment]
Hi there,
Probably not possible, this gem is for interacting with the mandrill api, so there are no local templates. Letter_opener appears to just render normal html/text emails sent from rails, which means the html and assets are all local to rails.

Theoretically, with mandrill's api you could build a gem that pulls down all the templates from a mandrill account and renders the emails by using data provided by this gem. A preview like that is out of the scope of this gem sadly, since this is essentially an api wrapper that acts like a normal rails mailer.

**Comment by renz45** [comment]
I forgot to mention, in development you can send test emails as documented here: https://github.com/renz45/mandrill_mailer#creating-a-test-method

This allows you to preview emails, while letting mandrill render them as you would see them.

**Comment by nmenag** [comment]
ok, thanks you
