### ISSUE TITLE
vars do not serialize properly when using deliver_later

### ISSUE THREAD

**Issue by AndKiel** [renz45/mandrill_mailer#123]
I've been implementing custom devise mailer using `MandrillMailer::TemplateMailer`.

I've overridden `send_devise_notification` method in my model as described in the devise documentation [here](https://github.com/plataformatec/devise#activejob-integration).

When keys in the `vars` hash passed to the `mandrill_mail` method are symbols, I get an error:

```
ActiveJob::SerializationError at /user/password
Unsupported argument type: Symbol
```

When I change keys to strings and use `'name' => value` notation, everything works.

I think that the problem is `template_content`. There are `global_merge_vars` there and values for `'name'` keys are symbols. There is no mention in the docs that keys in `vars` must be strings and symbols cannot be used. Fix or update in the docs would be nice.

**Comment by renz45** [comment]
Hi there, I'm sorry for taking so long to respond. I've been traveling for the past week and it's taken a bit to catch up on emails.

It seems like this error is related to how ActiveJob serializes objects. From a quick glance through ActiveJob it looks like in certain situations it doesn't like to serialize symbols. Here is a list from the source on accepted objects: https://github.com/rails/rails/blob/dd7d5b7c800b4f6d32747913fc7c8d00ce94f03a/activejob/lib/active_job/arguments.rb#L38

Devise probably works by default since it sets ActionMailer as it's default mailer, which is part of Rails and is designed to work with any changes to ActiveJob. This lib is designed to mimic the mailer syntax, but doesn't use it directly like Devise. That being said, if you wanted to submit a PR to the README with a general solution of what you did, specific to ActiveJob I'll merge it in. :)

**Comment by raphaelpra** [comment]
I had a similar issue and I have implemented a workaround by stringifying all arguments.

Is it something acceptable, or are they any drawbacks that I haven't thought ?
